using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using ReadmeSync.Models;

namespace ReadmeSync.Services
{
    /// <summary>
    /// Service responsible for generating markdown documentation.
    /// </summary>
    public class MarkdownGenerator
    {
        /// <summary>
        /// Generates the complete markdown file, preserving manual content above the marker.
        /// </summary>
        public void GenerateMarkdown(
            string outputFile,
            IEnumerable<IGrouping<string, CodeFileInfo>> fileGroups,
            string language,
            string fileExtension,
            bool useEmojis,
            string repoUrl)
        {
            // Preserve manual section
            string manual = PreserveManualContent(outputFile);

            // Compute statistics
            int nsCount = fileGroups.Count();
            int classCount = fileGroups.Sum(g => g.Count());
            int methodCount = fileGroups.Sum(g => g.SelectMany(c => c.Methods).Count());
            int todoCount = fileGroups.Sum(g => g.SelectMany(c => c.Todos).Count());

            // Write the markdown file
            using var sw = new StreamWriter(outputFile, false);
            
            WriteHeader(sw, manual, language, useEmojis);
            WriteStatistics(sw, nsCount, classCount, methodCount, todoCount, useEmojis);
            WriteNamespaces(sw, fileGroups, fileExtension, useEmojis);
        }

        /// <summary>
        /// Generates markdown content as a string without writing to file (dry-run preview).
        /// </summary>
        public string PreviewMarkdown(
            IEnumerable<IGrouping<string, CodeFileInfo>> fileGroups,
            string language,
            string fileExtension,
            bool useEmojis,
            string repoUrl)
        {
            var sb = new StringBuilder();

            int nsCount = fileGroups.Count();
            int classCount = fileGroups.Sum(g => g.Count());
            int methodCount = fileGroups.Sum(g => g.SelectMany(c => c.Methods).Count());
            int todoCount = fileGroups.Sum(g => g.SelectMany(c => c.Todos).Count());

            WriteHeaderToBuilder(sb, language, useEmojis);
            WriteStatisticsToBuilder(sb, nsCount, classCount, methodCount, todoCount, useEmojis);
            WriteNamespacesToBuilder(sb, fileGroups, fileExtension, useEmojis);

            return sb.ToString();
        }

        private string PreserveManualContent(string outputFile)
        {
            if (!File.Exists(outputFile))
                return "";

            string existing = File.ReadAllText(outputFile);
            int marker = existing.IndexOf("<!-- AUTO-GENERATED BELOW");
            
            return marker >= 0 ? existing[..marker].TrimEnd() + "\n\n" : "";
        }

        private void WriteHeader(StreamWriter sw, string manual, string language, bool useEmojis)
        {
            sw.WriteLine(manual);
            sw.WriteLine("<!-- AUTO-GENERATED BELOW – DO NOT EDIT -->");

            string titleEmoji = useEmojis ? "🧮 " : "";
            sw.WriteLine($"\n# {titleEmoji}Code Overview (auto-generated)\n");
            sw.WriteLine("This section is automatically generated by [ReadmeSync](https://github.com/tombomeke-ehb/ReadmeSync)\n");
            sw.WriteLine("Made by tombomeke Studios. To update, run the ReadmeSync tool locally.\n");
            sw.WriteLine($"_Language: **{language.ToUpper()}**_");
            sw.WriteLine($"_Last updated: **{DateTime.Now:yyyy-MM-dd HH:mm}**_\n");
        }

        private void WriteHeaderToBuilder(StringBuilder sb, string language, bool useEmojis)
        {
            sb.AppendLine("<!-- AUTO-GENERATED BELOW – DO NOT EDIT -->");

            string titleEmoji = useEmojis ? "🧮 " : "";
            sb.AppendLine($"\n# {titleEmoji}Code Overview (auto-generated)\n");
            sb.AppendLine("This section is automatically generated by [ReadmeSync](https://github.com/tombomeke-ehb/ReadmeSync)\n");
            sb.AppendLine("Made by tombomeke Studios. To update, run the ReadmeSync tool locally.\n");
            sb.AppendLine($"_Language: **{language.ToUpper()}**_");
            sb.AppendLine($"_Last updated: **{DateTime.Now:yyyy-MM-dd HH:mm}**_\n");
        }

        private void WriteStatistics(StreamWriter sw, int nsCount, int classCount, int methodCount, int todoCount, bool useEmojis)
        {
            string statsEmoji = useEmojis ? "📊 " : "";
            sw.WriteLine($"{statsEmoji}**{nsCount} Packages · {classCount} Types · {methodCount} Methods · {todoCount} TODOs**\n");
            sw.WriteLine("");
        }

        private void WriteStatisticsToBuilder(StringBuilder sb, int nsCount, int classCount, int methodCount, int todoCount, bool useEmojis)
        {
            string statsEmoji = useEmojis ? "📊 " : "";
            sb.AppendLine($"{statsEmoji}**{nsCount} Packages · {classCount} Types · {methodCount} Methods · {todoCount} TODOs**\n");
            sb.AppendLine("");
        }

        private void WriteNamespaces(StreamWriter sw, IEnumerable<IGrouping<string, CodeFileInfo>> fileGroups, string fileExtension, bool useEmojis)
        {
            string[] emojis = { "🧱", "⚔️", "🧙", "🏹", "🐉", "🏰", "🧭", "🪄", "🧰", "🎯", "📦", "🧩" };
            int eIndex = 0;

            foreach (var nsGroup in fileGroups)
            {
                string nsPrefix = useEmojis ? $"{emojis[eIndex++ % emojis.Length]} " : "";
                sw.WriteLine($"\n## {nsPrefix}{nsGroup.Key}\n");

                foreach (var file in nsGroup)
                {
                    WriteClassSection(sw, file, fileExtension);
                }
            }
        }

        private void WriteNamespacesToBuilder(StringBuilder sb, IEnumerable<IGrouping<string, CodeFileInfo>> fileGroups, string fileExtension, bool useEmojis)
        {
            string[] emojis = { "🧱", "⚔️", "🧙", "🏹", "🐉", "🏰", "🧭", "🪄", "🧰", "🎯", "📦", "🧩" };
            int eIndex = 0;

            foreach (var nsGroup in fileGroups)
            {
                string nsPrefix = useEmojis ? $"{emojis[eIndex++ % emojis.Length]} " : "";
                sb.AppendLine($"\n## {nsPrefix}{nsGroup.Key}\n");

                foreach (var file in nsGroup)
                {
                    WriteClassSectionToBuilder(sb, file, fileExtension);
                }
            }
        }

        private void WriteClassSection(StreamWriter sw, CodeFileInfo file, string fileExtension)
        {
            string typeLabel = string.IsNullOrEmpty(file.TypeKeyword) ? "class" : file.TypeKeyword;
            if (!string.IsNullOrEmpty(file.Link))
                sw.WriteLine($"### [{file.Class}{fileExtension}]({file.Link}) *({typeLabel})*");
            else
                sw.WriteLine($"### `{file.Class}{fileExtension}` *({typeLabel})*");

            if (!string.IsNullOrEmpty(file.Inheritance))
                sw.WriteLine($"**Inherits:** `{file.Inheritance}`\n");

            if (!string.IsNullOrEmpty(file.Summary))
                sw.WriteLine($"> {file.Summary}\n");

            if (file.Methods.Any())
            {
                sw.WriteLine("**Public Methods:**");
                foreach (var m in file.Methods)
                    sw.WriteLine($"- `{m}()`");
            }
            else
                sw.WriteLine("_No public methods found._");

            if (file.Todos.Any())
            {
                sw.WriteLine("\n**TODOs:**");
                foreach (var todo in file.Todos)
                    sw.WriteLine($"- [ ] {todo}");
            }

            sw.WriteLine();
        }

        private void WriteClassSectionToBuilder(StringBuilder sb, CodeFileInfo file, string fileExtension)
        {
            string typeLabel = string.IsNullOrEmpty(file.TypeKeyword) ? "class" : file.TypeKeyword;
            if (!string.IsNullOrEmpty(file.Link))
                sb.AppendLine($"### [{file.Class}{fileExtension}]({file.Link}) *({typeLabel})*");
            else
                sb.AppendLine($"### `{file.Class}{fileExtension}` *({typeLabel})*");

            if (!string.IsNullOrEmpty(file.Inheritance))
                sb.AppendLine($"**Inherits:** `{file.Inheritance}`\n");

            if (!string.IsNullOrEmpty(file.Summary))
                sb.AppendLine($"> {file.Summary}\n");

            if (file.Methods.Any())
            {
                sb.AppendLine("**Public Methods:**");
                foreach (var m in file.Methods)
                    sb.AppendLine($"- `{m}()`");
            }
            else
                sb.AppendLine("_No public methods found._");

            if (file.Todos.Any())
            {
                sb.AppendLine("\n**TODOs:**");
                foreach (var todo in file.Todos)
                    sb.AppendLine($"- [ ] {todo}");
            }

            sb.AppendLine();
        }
    }
}
